name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
